print("hello,i'm kiryu (˶ˆᗜˆ˵) ")
name = input ("what's your name ?")
print(name + " ,that's a cute name (˶ᵔ ᵕ ᵔ˶) ")
age = int(input("i am 16 years old, you? "))
print(f"so, {name} you are {age} now")
print(f"so, next year you will be {age + 1} years old")
print("happy early birthday " +  name + "(˶˃ ᵕ ˂˶)")
print("yay you finish your work ≽^•⩊•^≼")